#!/bin/bash

# generate_theme.sh
# author: RLovelessIII
# description: Automate theme changing on Manjaro-i3

############
## Config ##
############

bgd_config="$HOME/.cache/wal/themeGen-wallpaper.conf";
dir=$(dirname "$0");
. ${dir}/themeGen.conf;

###############
## Variables ##
###############

alpha=70;
background_name="lock-screen.jpg";
background="/usr/share/backgrounds/${background_name}";
# Oomox's theme/icon changing scripts
oomox_theme_script="/opt/oomox/plugins/theme_arc/arc-theme/change_color.sh";
oomox_icons_script="/opt/oomox/plugins/icons_papirus/change_color.sh";
# Directory & files generated by Pywal for color scheme
colors_dir="$HOME/.cache/wal/";
colors_oomox="${colors_dir}colors-oomox"
colors_gtk="${colors_dir}gtk-${theme_name}.xml";
# GTK-3 theme directory
gtk3_themes_dir="/usr/share/gtksourceview-3.0/styles/";
# Script that updates any JetBrains IDE color scheme to match Pywal color gen
intellij_script="$HOME/.scripts/intellijPywalGen/intellijPywalGen.sh";
# Config files for each JetBrains IDE
intellij_conf="$HOME/.IntelliJIdea2019.1/config";
webstorm_conf="$HOME/.WebStorm2019.1/config";

############
## Script ##
############

if zenity --question \
  --title="Theme Generator" \
  --text="Would you like to select select a specific wallpaper?\nSelect no for random." \
	--no-wrap;
then
  photo=$(zenity --file-selection);
else
  photo=$photo_dir;
fi

while true; do
	(
	echo "# Generating theme..." ; sleep 1
	wal -c;
	wal -a $alpha -i $photo;
    	) |
		zenity --progress \
	  	--title="Generate Theme" \
	  	--text="Generating Pywal color-scheme..." \
	  	--pulsate \
	  	--auto-close;

	if zenity --question \
		--text="Would you like to use this theme?" \
		--no-wrap;
	then
		cp $bgd_config $dir;
		break;
	fi
done

# path to wallpaper => $wallpaper
. ${dir}/themeGen-wallpaper.conf;

(
echo "# Getting things ready..." ; sleep 4
gksu $dir/permissions.sh $colors_gtk $gtk3_themes_dir $wallpaper $background;
echo "# Updating color-scheme..." ; sleep 4
echo "# Updating widgets..." ; sleep 1
$oomox_theme_script -o $theme_name $colors_oomox;
echo "# Updating icons..." ; sleep 1
$oomox_icons_script -o $theme_name $colors_oomox;
echo "# Updating JetBrains color-scheme..." ; sleep 4
$intellij_script $intellij_conf;
$intellij_script $webstorm_conf;
echo "# Applying theme..." ; sleep 5
) |
zenity --progress \
	--title="Generate Theme" \
  --text="Generating Pywal color-scheme..." \
	--pulsate \
	--time-remaining \
	--auto-kill \
	--auto-close;

if zenity --question \
	--text="Complete! Changes won't take full effect until your next session.\nWould you like to logout now?" \
	--no-wrap;
then
	i3exit logout;
else
	i3-msg restart;
fi

exit 0
