#!/usr/bin/env bash

# macos/apply_theme.sh
# author: Richard Loveless III (RLovelessIII)
# description: Script that applies a new theme to MacOS 10.15 Beta

# Get current Operating System
DIR=$(dirname "$0");

############
## Config ##
############

# # # # # # # #
#  macos.conf #
# # # # # # # #
. "${DIR}"/config/macos.conf;
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#  $wallpaper_directory = Default directory for wallpapers                            #
#  $wal_colors = File generated by Pywal with theme colors & wallpaper variables      #
#  $intellij_script = Updates Jetbrains IDE themes using the color-scheme from Pywal  #
#  $idea_config = Path to Intellij's config                                           #
#  $webstorm_config = Path to Webstorm's config                                       #
#  $pycharm_config = Path to Pycharm's config                                         #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

###############
## Variables ##
###############

# Retrieve 1st arg (photo name) and append it to $wallpaper_directory
photo_name=${1}
path_to_photo=${wallpaper_directory}${photo_name};

# Include Pywal executable path for remote execution
wal="/usr/local/bin/wal";

############
## Script ##
############

# Clear out current color-scheme cache
${wal} -c;
# Use Pywal (wal) to generate theme colors and set desktop wallpaper
# -i path to photo used for color generation
# --iterative used if choosing a random wallpaper, this will select the next wallpaper rather than a random one each time
${wal} -i "${path_to_photo}" --iterative;

# Execute IntelliJPywal script to update Jetbrains' IDE themes
${intellij_script} ${idea_config};
${intellij_script} ${webstorm_config};
${intellij_script} ${pycharm_config};

exit 0;