#!/usr/bin/env bash

# linux/apply_theme.sh
# Author: RLovelessIII
# Description: Script that applies the newly generated theme

# Get current directory
DIR=$(dirname "$0")

############
## Config ##
############

# # # # # # # # # # #
#  manjaro_i3.conf  #
# # # # # # # # # # #
. "${DIR}"/config/manjaro_i3.conf
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#  $theme_name = Name for generated themes                                            #
#  $lock_screen = Path to image used in the greeter                                   #
#  $gtk3_themes_directory = Path to GTK3 color-scheme directory                       #
#  $wal_colors = File generated by Pywal with theme colors & wallpaper variables      #
#  $wal_colors_gtk = File generated from template for GTK3 theme                      #
#  $wal_colors_oomox = File generated from template for Oomox theme/icons             #
#  $oomox_theme_script = Updates Oomox theme using the color-scheme from Pywal        #
#  $oomox_icons_script = Updates Oomox icons using the color-scheme from Pywal        #
#  $intellij_script = Updates Jetbrains IDE themes using the color-scheme from Pywal  #
#  $idea_config = Path to Intellij's config                                           #
#  $webstorm_config = Path to Webstorm's config                                       #
#  $pycharm_config = Path to Pycharm's config                                         #
#  $remote_host = Name of remote PC to sync theme                                     #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# # # # # # # # #
# ${wal_colors} #
# # # # # # # # #
. "${wal_colors}"
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#  $wallpaper = Local path to wallpaper used for theme  #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #

############
## Script ##
############

(
echo "# Getting things ready..." ; sleep 4 # Sleep for [default: 4] seconds to emulate a working process
# Uses the gui prompt to execute permissions.sh as root
gksu "${DIR}"/permissions.sh "${wal_colors_gtk}" "${gtk3_themes_directory}" "${wallpaper}" "${lock_screen}"
echo "# Updating theme..." ; sleep 1
# Use Oomox to update WM theme (widgets, windows, etc)
"${oomox_theme_script}" -o "${theme_name}" "${wal_colors_oomox}"
echo "# Updating icons..." ; sleep 1
# Use Oomax to update system icons: mainly directory icons
"${oomox_icons_script}" -o "${theme_name}" "${wal_colors_oomox}"
echo "# Updating JetBrains color-scheme..." ; sleep 4
# Execute IntelliJPywal script to update Jetbrains' IDE themes
"${intellij_script}"
echo "# Applying theme..." ; sleep 5
) |
zenity --progress \
    --title="Generate Theme" \
	  --pulsate \
	  --time-remaining \
	  --auto-kill \
	  --auto-close;

# Prompt to update remote host's theme using the same wallpaper
# DISCLAIMER: To be able to run this script W/O the use of a terminal, ssh-keygen pair must be
#             established to prevent password prompt for connection.
if zenity --question \
    --text="Complete! Would you also like to update \"${remote_host}\" using this theme?" \
    --no-wrap;
then
    # Use IFS to split the wallpaper path by the '/' delimeter into an array variable
    # Retrieve the last index of the array (name of the wallpaper)
    IFS='/' read -r -a  path_to_wallpaper <<< "${wallpaper}";
    wallpaper=${path_to_wallpaper[-1]};

    # Alias 'update-theme' is located on remote machine which executes themeGen/launch.sh
    # This prevents the need to establish which shell, or executeable paths we need for the remote-host,
    # we echo two commands
    #      1. Using the remote alias to update the theme passing the name of the wallpaper
    #      2. Terminate connection to the remote-host
    # Echoing the commands enables terminal interaction without the need to specifiy executable paths
    # -tt is used to force a psuedo-terminal during the session to allow the use of stdin with shh
    echo "update-theme ${wallpaper}; exit;" | ssh -tt ${remote_host};
fi

# Prompt user if they would like to restart their session
# GTK3 themes will NOT be applied until AFTER new session
if zenity --question \
    --text="Complete! Changes won't take full effect until your next session.\nWould you like to logout now?" \
    --no-wrap;
then
    # End session and logout
	  i3exit logout;
else
    # Reload i3 to initiate most changes
	  i3-msg restart;
fi

exit 0;